### ISSUE TITLE
Plugin Database Access Denied Error

### ISSUE THREAD

**Issue by ghost** [bs-community/bs-integration-for-wordpress#1]
Hello, ive encountered an Error with the Plugin.
![image](https://user-images.githubusercontent.com/3518022/65836011-f7a83c80-e31f-11e9-97b4-2ce41daa272f.png)

The Username , Password, Database information are all correct. Blessing Skins server is using the same details and it works but for the Plugin, access is denied.

The only difference for Blessing Skins server, is that Blessing Skins server uses the Web Server "IP" for the "Database Host" instead of 'localhost'

If i use the Web Server "IP" instead for the Plugin's Database Host, i get this error.

![image](https://user-images.githubusercontent.com/3518022/65836054-92a11680-e320-11e9-8dbc-50ee8f6501f1.png)

Also, how does the Plugin handle Password syncing? Because Wordpress uses a different Password Hashing method that's not on the options list for Password Hashing method.

Hopefully you can help with this issue, thank you.

**Comment by g-plane** [comment]
If your WordPress server and MySQL server aren't on the same host, you may configure your MySQL to make it allow to accept external connections.

**Comment by g-plane** [comment]
Closing since there're no responses.
